### ISSUE TITLE
error with non-blocking I/O

### ISSUE THREAD

**Issue by andysc** [bluerhinos/phpMQTT#12]
After publishing around 1000 messages in quick succession, PHP client reports 
errno 32, broken pipe. 

Also seeing (on other runs of same app)...

Notice: fwrite(): send of 2 bytes failed with errno=11 Resource 
temporarily unavailable in phpMQTT.php

I suspect this is to do with the non-blocking socket I/O in phpMQTT, as errno 11 is EAGAIN. But this does not appear to be handled by the library.

Is there a particular reason for using NBIO, and if so, could the library handly EAGAIN a bit better, please ? :)

**Comment by bluerhinos** [comment]
> I am restarting this project so having a clear out of old issues (If you believe this is still valid please reopen)

Sorry for delay, I don't this this is still a problem as I cannot repeat (with 10000s of publishes)
