### ISSUE TITLE
mqtt mysql 

### ISSUE THREAD

**Issue by pw44** [bluerhinos/phpMQTT#125]
trying to have mysql performing a query based on the mqtt topic.

$mqtt = new Bluerhinos\phpMQTT($server, $port, $client_id);
if(!$mqtt->connect(true, NULL, $username, $password)) {
        exit(1);
}

mysql_connect( $mysql_host, $mysql_user, $mysql_pass ) or die( ' Erro na conexão ' );

$mqtt->debug = true;

$topics['bluerhinos/phpMQTT/examples/publishtest'] = array('qos' => 0, 'function' => 'procMsg');
$mqtt->subscribe($topics, 0);

while($mqtt->proc()) {

}

$mqtt->close();

function procMsg($topic, $msg){
                echo 'Msg Recieved: ' . date('r') . "\n";
                echo "Topic: {$topic}\n\n";
                echo "\t$msg\n\n";

is not working... error: 

PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /home/paulo/TOOLS/MQTT-PHP/subscribe-mysql.php:27
Stack trace:
#0 {main}
  thrown in /home/paulo/TOOLS/MQTT-PHP/subscribe-mysql.php on line 27

any clue?

**Comment by anhlephuoc** [comment]
Your problem is unrelated to this MQTT library!
The function you used "mysql_connect()" was deprecated since PHP5. It has been removed from PHP7.
Please look the up the manual pages and use the alternative suggestion.

**Comment by pw44** [comment]
Thank you for pointing out, mysql should read mysqli, and another 
problem arised:

by the following code, after paylod is read,

question is if it's possible to perform other funcions inside the 
procMsg, depending on received payload for topic.

------------------------------------------------
$mysql_mydb = 'rfid-cards';

$mqtt = new Bluerhinos\phpMQTT($server, $port, $client_id);
if(!$mqtt->connect(true, NULL, $username, $password)) {
   echo "Failed to connect to Mqtt: ";
   exit(1);
}

$mysqli = new mysqli($mysql_host, $mysql_user, $mysql_pass, $mysql_mydb );
if ($mysqli -> connect_errno) {
   echo "Failed to connect to MySQL: " . $mysqli -> connect_error;
   exit(2);
}
PHP Fatal error:  Uncaught Error: Call to a member function query() on

$mqtt->debug = true;

$topics['rfid/card/ping'] = array('qos' => 0, 'function' => 'procMsg');
$mqtt->subscribe($topics, 0);

while($mqtt->proc()) {

}

$mqtt->close();

function procMsg($topic, $msg){
                 echo 'Msg Recieved: ' . date('r') . "\n";
                 echo "Topic: {$topic}\n";
                 echo "Payload: {$msg}\n";

                 // Perform query
                 if ($result = $mysqli -> query("SELECT * FROM 
rfid-cards")) {
                   echo "Returned rows are: " . $result -> num_rows;
                   // Free result set
                   $result -> free_result();
                 }

                 $mysqli -> close();

}
---------------------------------------------


***@***.***:~/TOOLS/MQTT-PHP$ php subscribe-mysql.php
Sun, 18 Jul 2021 14:42:13 -0300: Received CMD: 3 (PUBLISH)
Sun, 18 Jul 2021 14:42:13 -0300: Fetching: 17 bytes
Msg Recieved: Sun, 18 Jul 2021 14:42:13 -0300
Topic: rfid/card/ping
Payload: 2
PHP Notice:  Undefined variable: mysqli in 
/home/paulo/TOOLS/MQTT-PHP/subscribe-mysql.php on line 48
PHP Fatal error:  Uncaught Error: Call to a member function query() on 
null in /home/paulo/TOOLS/MQTT-PHP/subscribe-mysql.php:48
Stack trace:
#0 [internal function]: procMsg()
#1 /home/paulo/TOOLS/MQTT-PHP/phpMQTT.php(482): call_user_func()
#2 /home/paulo/TOOLS/MQTT-PHP/phpMQTT.php(547): 
Bluerhinos\phpMQTT->message()
#3 /home/paulo/TOOLS/MQTT-PHP/subscribe-mysql.php(36): 
Bluerhinos\phpMQTT->proc()
#4 {main}
   thrown in /home/paulo/TOOLS/MQTT-PHP/subscribe-mysql.php on line 48

**Comment by pw44** [comment]
my fault.
