### ISSUE TITLE
PHP server hangs after few MQTT publish requests

### ISSUE THREAD

**Issue by lunanigra** [bluerhinos/phpMQTT#24]
Hello, I would like to use your MQTT lib to publish commands against IBM Bluemix.

Basically it works fine. But after several call the whole PHP instance hangs. I assume that there is a small mistake in integrating the lib.

I your sample the connection is closed after publishing the command. Is there a way to keep the connection open? Idee is a PHP script called via Ajax. Hope this makes sense.

Thanks!

**Comment by bluerhinos** [comment]
> I am restarting this project so having a clear out of old issues (If you believe this is still valid please reopen)

I am going to add a subscribeAndWaitForMessage function that could help the Ajax use case
