### ISSUE TITLE
establishment

### ISSUE THREAD

**Issue by sissad** [bluerhinos/phpMQTT#25]
Hi,
I habe MQTT server installed on Synology NAS and work fine.

I have the oublishing phpMQTT.php Script an work fine to.
But the subscrib script give error:
Fatal error: Maximum execution time of 60 seconds exceeded in C:\Inetpub\vhosts\user.com\httpdocs\phpMQTT.php on line 309

Can you help me set up correctly?

Thank you in advance
David

**Comment by bluerhinos** [comment]
> I am restarting this project so having a clear out of old issues (If you believe this is still valid please reopen)

Canned Response: Subscribe is not designed for web requests, it should be used in a long running process.
I do plan to add a subscribeAndWaitForMessage() function #95
