### ISSUE TITLE
Not able to connect with MQTT Server.

### ISSUE THREAD

**Issue by anil1712** [bluerhinos/phpMQTT#28]
Hi,
I am getting below error while running `publish.php`. Please help me to resolve this. What could be the exact reasone for this. I have my server IP and port. (I dont' have $username and $password so kept it blank, only passing the IP, port and clientId.

<code>
Notice: Uninitialized string offset: 0 in C:\xampp\htdocs\mqtt\phpMQTT.php on line 141
</code>
<code>
Notice: Uninitialized string offset: 0 in C:\xampp\mqtt\phpMQTT.php on line 145
</code>
<code>
Notice: Uninitialized string offset: 3 in C:\xampp\mqtt\phpMQTT.php on line 145
</code>
<code>
Fail or time out
</code>

Please help me to solve this.
FYI: I checked the same thing in my localhost and server both but getting same output.

**Comment by alaendle** [comment]
Since I've encountered the same problem - my guess is that this might happen in case the server only gets half of the CONNECT telegram in it's input buffer. To minimize the chance that this happens you might want to change...

        fwrite($this->socket, $head, 2);
        fwrite($this->socket, $buffer);

to

        fwrite($this->socket, $head . $buffer);

in function connect.

**Comment by harkalygergo** [comment]
Try 1883 port or something else, this solved me the same problem.

**Comment by kamilsweb** [comment]
Getting this error Warning: stream_socket_client(): unable to connect to tcp://localhost:1883 (Connection refused).

I'm missing anything?
Do I need to configure the mosquitto-php too I'm using PHPMqtt?
Do I need to configure the broker too, if yes then please help in this?

**Comment by harkalygergo** [comment]
kamilsweb, is 1883 port open on localhost? Is MQTT running on localhost?

**Comment by kamilsweb** [comment]
@harkalygergo Thanks for prompt response. 
I'm not sure about port so tested with port 80 too, also tried with other open ports too but no luck.

And I'm not sure about MQTT Installation, how could I check this? and if not then how to Install?

**Comment by kamilsweb** [comment]
@harkalygergo I'm naive to the tcp protocol, I have just followed this repo  https://github.com/bluerhinos/phpMQTT

**Comment by bluerhinos** [comment]
> I am restarting this project so having a clear out of old issues (If you believe this is still valid please reopen)
