### ISSUE TITLE
Socket error connection on client

### ISSUE THREAD

**Issue by srikodali-eruvaka** [bluerhinos/phpMQTT#29]
MQTT is working fine by running my php file in background process. But suddenly after few days it is throwing error like "Socket error on client client_name, disconnecting". After that error php file which is running in background stopped. Can any one help me to solve this issue?

**Comment by srikodali-eruvaka** [comment]
MQTT is working fine by running my php file in background process. But suddenly after few days it is throwing error like "Socket error on client client_name, disconnecting". After that error php file which is running in background stopped. Can any one help me to solve this issue?

**Comment by laurentdinclaux** [comment]
I have the exact same issue after a few days ...

**Comment by greenpeas** [comment]
use public $debug = true; 
You will see "eof receive going to reconnect for good measure"
https://github.com/bluerhinos/phpMQTT/blob/master/phpMQTT.php#L310
I do not know how to solve this problem :(

**Comment by dtbaker** [comment]
I just ran into this, I was listening on too many topics at once. Cutting it back to 4 topics (from 10) worked

**Comment by bluerhinos** [comment]
> I am restarting this project so having a clear out of old issues (If you believe this is still valid please reopen)

Some recent changes may of fixed this.
