### ISSUE TITLE
Subscribe did not work 

### ISSUE THREAD

**Issue by hkachhia** [bluerhinos/phpMQTT#30]
Subscribe does not work. It gave wrong subscribe header error.
And continuously connect and disconnect from server.

function proc()
Every time it's print "eof receive going to reconnect for good measure\n"; Means nothing to read from channel and go to eof socket

**Comment by nedimhx** [comment]
I have blank page on subscribe, but publishing is fine...

Did you @hkachhia solve the issue?

**Comment by aggarwalsri** [comment]
Also, it doesn't works from command line

**Comment by Jake-Hu** [comment]
I also have the same problem.

**Comment by nedimhx** [comment]
Hey guys... I don't know why, but from console when I run 
php sub.php it works!

As I need that sript to add RFID card,  I put break in sub.php code so script will stop on first recieved from my nodemcu.
And like that I call it with shell_exec("sudo php /$user/$node_id/sub.php"); from my other php file

**Comment by parispring** [comment]
@nedimhx  , Subscribe did not work  even from  console  in windows7,    must run at linux?

**Comment by nedimhx** [comment]
I have successfully run it on linux console as I mention before


On June 7, 2018 11:30:48 parispring <notifications@github.com> wrote:

@nedimhx<https://github.com/nedimhx> , Subscribe did not work even from console in windows7, must run at linux?

**Comment by kingtiwns** [comment]
you can replace statement $cmd = 0x80; with $cmd = 0x82; in subscribe function

**Comment by qqskynet** [comment]
> 
> 
> you can replace statement $cmd = 0x80; with $cmd = 0x82; in subscribe function

great! it works!

**Comment by mekodak** [comment]
I got my "publich.php" working by erase "namespace Bluerhinos;" from "phpMQTT.php"

But i can't get "subscribe.php" to work i keep getting (504) and i have tryed to 

> you can replace statement $cmd = 0x80; with $cmd = 0x82; in subscribe function

But still same (504) error.

**Comment by jeroenst** [comment]
replace the publish function with:         

/* subscribe: subscribes to topics */
        function subscribe($topics, $qos = 0){
                foreach($topics as $key => $topic){
                        $i = 0;
                        $buffer = "";
                        $id = $this->msgid;
                        $buffer .= chr($id >> 8);  $i++;
                        $buffer .= chr($id % 256);  $i++;
                        $buffer .= $this->strwritestring($key,$i);
                        $buffer .= chr($topic["qos"]);  $i++;
                        $this->topics[$key] = $topic; 
                
                        $cmd = 0x80;
                        //$qos
                        $cmd += ($qos << 1);

                        $head = chr($cmd);
                        $head .= chr($i);
                
                        fwrite($this->socket, $head, 2);
                        fwrite($this->socket, $buffer, $i);
                        fflush($this->socket);
                }
        }

**Comment by mekodak** [comment]
Dont change anything
Loading for some time an then (504)

**Comment by bluerhinos** [comment]
> I am restarting this project so having a clear out of old issues (If you believe this is still valid please reopen)

Recent updates may of fixed this
