### ISSUE TITLE
I think this couldn't keep a session for more than $keepalive time.

### ISSUE THREAD

**Issue by n-hirano** [bluerhinos/phpMQTT#31]
Why is $timesinceping updated by receiving data?
To do keepalive, we need to SEND data to sever(broker) repeatedly.
So, receiving data shouldn't affect the keepalive responses' algorithm.
when a client is just a subscriber, it should send ping repeatedly within $keepalive time, otherwise it will loose sessions and needs to reconnect.

To cofirm the opinion above, you could do the following.
Turn the debug flag on and subscribe a topic which is published messages every second,
you'll see the debug message "eof receive going to reconnect for good measure\n" periodically (in every $keepalive time).

**Comment by n-hirano** [comment]
I'll show my source code. It would help clarify my point.
From the line No.336 in phpMQTT.php(.txt), I modified.
The keyword is "timesinceping".
[phpMQTT.php.txt](https://github.com/bluerhinos/phpMQTT/files/507801/phpMQTT.php.txt)

**Comment by bluerhinos** [comment]
> I am restarting this project so having a clear out of old issues (If you believe this is still valid please reopen)
