### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by anil1712** [bluerhinos/phpMQTT#37]
Hi,

I did the same as per the documentation but getting below exception.
```
PHP Warning:  fsockopen(): unable to connect to wss://mydomain.com:1883 (Unable to find the socket transport &quot;wss&quot; - did you forget to enable it when you configured PHP?)
```
@bluerhinos Please help me to out of it.

**Comment by bluerhinos** [comment]
> I am restarting this project so having a clear out of old issues (If you believe this is still valid please reopen)
