### ISSUE TITLE
QoS > 0?

### ISSUE THREAD

**Issue by StreamingMeeMee** [bluerhinos/phpMQTT#39]
I've been able to successfully publish QoS1 msgs to Mosquito just fine.  However, the subs, also using QoS1, keep receiving the same messages over and over again.  Does phpMQTT send the PUBACK back to the broker?

**Comment by charanpahariapp** [comment]
I have subscribed my topic using QOS 1 after it I am receiving duplicated message continuously. How to send PUBACK pack??

**Comment by bluerhinos** [comment]
> I am restarting this project so having a clear out of old issues (If you believe this is still valid please reopen)

Feature request for QOS > 1 #4
