### ISSUE TITLE
Subscribe not working (VerneMQ Broker)

### ISSUE THREAD

**Issue by kovinet** [bluerhinos/phpMQTT#41]
I can successfully publish messages (I know this because when subscribed with other clients I also receive messages), but I don't receive any messages while subscribed with example provided.

I run the script as cli. With debug set on true I get following output every second:

> eof receive going to reconnect for good measure

but no messages. Also if I trace this client on broker I don't see any SUBSCRIBE calls from this client, only CONNECT calls.

**Comment by psorowka** [comment]
The lib (and all forks of it, obviously) send an invalid header in the subscribe package. Find & replace `0x80` with `0x82` and you'll be good to go.

Unfortunately I have not the time and php experience to make a pull request here

**Comment by bluerhinos** [comment]
> I am restarting this project so having a clear out of old issues (If you believe this is still valid please reopen)

Some recent changes may have fixed this
