### ISSUE TITLE
Update the examples

### ISSUE THREAD

**Issue by ganeshpulsars** [bluerhinos/phpMQTT#45]
Please update the examples like so (insert namespace) :
$mqtt = new Bluerhinos\phpMQTT($server, $port, $client_id);

**Comment by Rasenmaehermann** [comment]
Thank you! this helped.
Before reading your post, I solved the namespace problem by inserting the following line into the example code right below the "require("phpMQTT.php");" line:

use Bluerhinos\phpMQTT;

As a PHP Noob im not sure which solution is more useful. time will tell. ;)

**Comment by bluerhinos** [comment]
> I am restarting this project so having a clear out of old issues (If you believe this is still valid please reopen)

**Comment by ganeshpulsars** [comment]
Updating the example would be useful to future users
BTW Thanks for the nice utility.
