### ISSUE TITLE
Uninitialized string offset

### ISSUE THREAD

**Issue by mokssr** [bluerhinos/phpMQTT#48]
I tried some tutorials and ended up getting same errors when running my file.
It says:
PHP Notice:  Uninitialized string offset: 0 in /var/www/html/mqtt/classes/phpMQTT.php on line 155
PHP Notice:  Uninitialized string offset: 0 in /var/www/html/mqtt/classes/phpMQTT.php on line 159
PHP Notice:  Uninitialized string offset: 3 in /var/www/html/mqtt/classes/phpMQTT.php on line 159
Connection failed! (Error: 0x00 0x00)

considering i'm new in this thing, please make it simple to understand.

**Comment by pascalwacker** [comment]
Same issue for me on Ubuntu 16.04 with PHP 7.1

**Comment by HasnaaWaked** [comment]
same issue :(

**Comment by rajeshafor** [comment]
Same Issue:(

**Comment by mohancs30** [comment]
same (--

**Comment by nikunjramani** [comment]
change on phpmqtt.php
	$buffer .= chr(0x00); $i++;
	$buffer .= chr(0x06); $i++;
	$buffer .= chr(0x4d); $i++;
	$buffer .= chr(0x51); $i++;
	$buffer .= chr(0x49); $i++;
	$buffer .= chr(0x73); $i++;
	$buffer .= chr(0x64); $i++;
	$buffer .= chr(0x70); $i++;
	$buffer .= chr(0x03); $i++;

to this
$buffer .= chr(0x00); $i++;
	$buffer .= chr(0x04); $i++;
	$buffer .= chr(0x4d); $i++;
	$buffer .= chr(0x51); $i++;
	$buffer .= chr(0x54); $i++;
	$buffer .= chr(0x54); $i++;
	$buffer .= chr(0x04); $i++;

**Comment by bluerhinos** [comment]
> I am restarting this project so having a clear out of old issues (If you believe this is still valid please reopen)
Some recent changes may have fixed this.

**Comment by billy-billy** [comment]
I also made this mistake. However, I don't report errors every time I run, but sometimes this problem occurs. Not often


if (ord($string{0}) >> 4 === 2 && $string{3} === chr(0)) this line
