### ISSUE TITLE
Class 'phpMQTT' not found

### ISSUE THREAD

**Issue by akshar001** [bluerhinos/phpMQTT#50]
Hello i don't know why i am getting this error...

**Comment by thomasvt1** [comment]
That's an easy fix! :)

Remove
`namespace Bluerhinos;`
From
`phpMQTT.php`

I hope this helps

**Comment by akshar001** [comment]
It does!! I have to hug you for that thanks a lot..

**Comment by starcruizer** [comment]
@thomasvt1 thankyou very much

**Comment by parispring** [comment]
$mqtt = new Bluerhinos\phpMQTT($server, $port, $client_id);

**Comment by starcruizer** [comment]
Thanks @parispring  it also worked !!

**Comment by manfer9559** [comment]
Advertencia : stream_socket_client (): no se puede conectar a tcp: //***.cloudmqtt.com: ***** (Conexión rechazada) en /home/********/public_html/****/phpMQTT-master/phpMQTT.php en la línea 89 Time out! 


Mi archivo publish.php es asi
![error](https://user-images.githubusercontent.com/43598676/46062628-c8755300-c140-11e8-8d0e-556f6a7379f5.png)

**Comment by akshar001** [comment]
Sorry for  not closint it soon it works very fine
