### ISSUE TITLE
How to receive messages

### ISSUE THREAD

**Issue by chcmq** [bluerhinos/phpMQTT#55]
How do you receive the returned message after you send it？

**Comment by markus-hsk** [comment]
You can subscripe to the same topic before you publish. And so you receive it shortly after you sent it. I did this in my application to be 100% sure, that it was really transferred to the broker.

**Comment by chcmq** [comment]
What functions should I use if I were to receive the phpMQTT class？

**Comment by bluerhinos** [comment]
Canned Response: Subscribe is not designed for web requests, it should be used in a long running process.
I do plan to add a subscribeAndWaitForMessage() function #95
