### ISSUE TITLE
Wrong format in variable $msg

### ISSUE THREAD

**Issue by huyle0110** [bluerhinos/phpMQTT#56]
Hi, I call subscribe successfull, but have issue : string response from broker in wrong format. It has NV01
NV01 is string that i published , a first char ? Why it appear  here ?  Thanks

**Comment by fyyang** [comment]
the same to you

**Comment by bluerhinos** [comment]
> I am restarting this project so having a clear out of old issues (If you believe this is still valid please reopen)
