### ISSUE TITLE
Issue with username length while opening a connection

### ISSUE THREAD

**Issue by alhaddad-nasry** [bluerhinos/phpMQTT#58]
I'm trying to use phpMQTT to connect to an MQTT broker on a RabbitMQ server with a 52-characters username, but it is failing with the below error. While the error is similar to the one mentioned in #48, I'm not sure if it is the same cause:

`Notice: Uninitialized string offset: 0 in /PATH_TO_PHP/phpMQTT.php on line 155
Notice: Uninitialized string offset: 0 in /PATH_TO_PHP/phpMQTT.php on line 159
Notice: Uninitialized string offset: 3 in /PATH_TO_PHP/phpMQTT.php on line 159
Connection failed! (Error: 0x00 0x00)`

The error does not occur if I trim the username to 28 characters. But if I use at least one more character (29 or above), the above error occurs again.
MQTT specification recommends a 12-characters or less for each of the username and password field. But the specification also specifies that this **is not** requirement.

The MQTT broker on RabbitMQ expects the username to be the concatenation of the virtual-host-name and the username, separated by a colon ":". So a long username is valid.
The password was not an issue even though it is 64 characters.
[Section 3.1 in MQTT v3.1 protocol specification](https://public.dhe.ibm.com/software/dw/webservices/ws-mqtt/mqtt-v3r1.html#connect):

> It is recommended that user names are kept to 12 characters or fewer, but it is not required.

The above issue occurs when connecting from phpMQTT to a RabbitMQ server or to a Mosquitto server. But the same credentials used from other clients to the same servers works normally.

**Comment by JorgeLiu** [comment]
感谢 终于找到原因了

**Comment by evandentremont** [comment]
I had fixed this issue and submitted a pull request like a year ago. https://github.com/bluerhinos/phpMQTT/pull/47/commits/e26d1e2907325523484c69c3b6600f1ae0ddf74a

It seems that newer versions of PHP are causing issues with this project. My code worked in production at the time, I no longer work with that company and am trying to use my patch somewhere else. Running into the same undefined offset issues as everyone else now.

**Comment by bluerhinos** [comment]
> I am restarting this project so having a clear out of old issues (If you believe this is still valid please reopen)

**Comment by lmureddu** [comment]
In the last few days, I was driven crazy by a bug regarding a very long password for a project that I follow (it was 1800 character as it was an access token). Finally, I found the solution, changing line 238 of phpMQTT.php:
fwrite($this->socket, $head,2);  => fwrite($this->socket, $head);

Hope this can help someone else.
