### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by rajeshafor** [bluerhinos/phpMQTT#59]
Hi, I'm trying to open the Publish and scriber page but i'm getting Error: 
**Fatal error: Class 'phpMQTT' not found in C:\xampp\htdocs\websockets\examples\subscribe.php on line 12** .

Links:

Publish : http://localhost/websockets/examples/publish.php

Subscribe : http://localhost/websockets/examples/subscribe.php

**Comment by bluerhinos** [comment]
> I am restarting this project so having a clear out of old issues (If you believe this is still valid please reopen)
