### ISSUE TITLE
Unable to subscribe

### ISSUE THREAD

**Issue by dilipsarkar** [bluerhinos/phpMQTT#6]
Hi,
I'm trying to use phpMQTT on my Windows7 machine using localhost. Apache & PHP setup is done by installing WAMP server. I'm running it as below - 
- On my Firefox browser, in one tab running "http://localhost/phpMQTT-master/examples/publish.php"
- In another tab running "http://localhost/phpMQTT-master/examples/subscribe.php"

Is my way of running correct?

I'm not getting published message in subscribed tab but getting following error -
" Fatal error: Maximum execution time of 30 seconds exceeded in C:\wamp\www\phpMQTT-master\phpMQTT.php on line 156".

I have also enabled debug, copy of which is attached.

However I have another Python MQTT client running in command prompt which is getting the publish message from publisher.php.

I'm new to this, could you please help me on this ?

Thanks,
Dilip

**Comment by srikodali-eruvaka** [comment]
I am unable to subscribe using either of the codes. Please can any one help me. I am using subscriber code on server keeping it as a cron job so that when ever I receive published data, I can subscribe it. But I am unable to do it. In the subscriber code inside procmsg function I added code to hit DB, but nothing working.

**Comment by siddhc** [comment]
@dilipsarkar : Your snippet works great.

For beginners :
In publish.php and subscribe.php, do replace : 
`$mqtt = new phpMQTT($server, $port, $client_id);`
by : 
```
use Bluerhinos\phpMQTT;
$mqtt = new phpMQTT($server, $port, $client_id);
```

**Comment by anupritdangi** [comment]
Hi,
I am new to all this, Kindly help me regarding this error- 
Fatal error: Class 'phpMQTT' not found in C:\wamp64\www\phpMQTT-master\examples\subscribe.php on line 12

**Comment by srikodali-eruvaka** [comment]
You need to import phpMQTT file in your php file using include/require(core PHP) or extends (if using MVC framework)

**Comment by sunilnimble2015** [comment]
Hi 
I also facing the issue.. when i run publish.php it connected successfully. But when i run the subscriber it going on infinite loop. No message show from publisher.


It is subscriber side code :- 
```
require("../phpMQTT.php");
$server = "localhost";     			// change if necessary
$port = 1883;                     	// change if necessary
$username = "";                   	// set your username
$password = "";                   	// set your password
$client_id = "server"; 				// make sure this is unique for connecting to sever - you could use uniqid()
$mqtt = new Bluerhinos\phpMQTT($server, $port, $client_id);
if(!$mqtt->connect()) {
	exit(1);
}
$topics['bluerhinos/phpMQTT/examples/publishtest'] = array("qos" => 0, "function" => "procmsg");
$mqtt->subscribe($topics, 0);
while($mqtt->proc()){}
$mqtt->close();
function procmsg($topic, $msg){

	echo "Msg Recieved: " . date("r") . "\n";
	echo "Topic: {$topic}\n\n";
	echo "\t$msg\n\n";
}
```
Publish and subscribe message using command prompt between two  terminals are working.Using command 
mosquitto_pub -t topic/state -m "Hello Test"

Can someone help me where i miss anything?
