### ISSUE TITLE
How Print subscribe received message on web page?

### ISSUE THREAD

**Issue by bhavikbhansali** [bluerhinos/phpMQTT#60]
I am trying to develop a web page which will print the received message from subscribing to the topic. but I am not able to do it can anyone please help me on this?

**Comment by TiSpace** [comment]
I'm trying to do a similar task by using the subscribe example. The only progress I'm getting is to set the retained flag so I'm able to receive all messages. In principle, it works BUT the loop would run forever (or at least a long time), not practical for showing up a website.
I've you're able to get the last messages and exiting right after, let me know - that's what I'm fighting for!!

**Comment by burdem** [comment]
Guys, could you find any way to print the recieved message? I need to parse and save data to DB, but still confused. 

> In principle, it works BUT the loop would run forever (or at least a long time), not practical for showing up a website.

**Comment by bhavikbhansali** [comment]
No still no progress from my side..... I am still finding the same solution.

**Comment by bhavikbhansali** [comment]
@TiSpace Can you please tell us some more details and the thing you did to get it?

**Comment by lxlin315** [comment]
I have the same problem，please answer，thanks

**Comment by devilwacause** [comment]
Php is not the route you want to go if you want to display the messages on a site.

Try using paho_mqtt.js for this task,  I've used it succesfully in the past to create a browser based client.

remember PHP is parsed by the server before it ever returns a line of code.

**Comment by bluerhinos** [comment]
> I am restarting this project so having a clear out of old issues (If you believe this is still valid please reopen)

Canned Response: Subscribe is not designed for web requests, it should be used in a long running process.
I do plan to add a subscribeAndWaitForMessage() function #95
