### ISSUE TITLE
Uninitialized string offset

### ISSUE THREAD

**Issue by rajeshafor** [bluerhinos/phpMQTT#61]
Notice: Uninitialized string offset: 0 in C:\xampp\htdocs\websockets\phpMQTT.php on line 121

Notice: Uninitialized string offset: 0 in C:\xampp\htdocs\websockets\phpMQTT.php on line 125

Notice: Uninitialized string offset: 3 in C:\xampp\htdocs\websockets\phpMQTT.php on line 125
Fail or time out.

I'm new to MQTT.  Please give solution for it.

**Comment by evandentremont** [comment]
I'm also experiencing this and trying to track it down. It looks like $this->read() isn't getting any data from the stream.

**Comment by kingtiwns** [comment]
phpmqtt only support mqttv3.1 ，not support v3.1.1，you must modify code

//MQTT v3.1.1协议名称长度 4
		$buffer .= chr(0x00); $i++;
		$buffer .= chr(0x04); $i++;
		// 4D 51 54 54 mqtt v3.1.1 协议名称
		// 4D 51 49 73 64 70 mqtt v3.0 协议名称
		$buffer .= chr(0x4d); $i++;
		$buffer .= chr(0x51); $i++;
		$buffer .= chr(0x54); $i++;
		$buffer .= chr(0x54); $i++;

		//mqtt v3.1.1 协议名称 版本号
		$buffer .= chr(0x04); $i++;

**Comment by taroyutao** [comment]
这个具体怎么调整呀，是把下面的源码部分
		
		$buffer .= chr(0x00); $i++;
		$buffer .= chr(0x06); $i++;
		$buffer .= chr(0x4d); $i++;
		$buffer .= chr(0x51); $i++;
		$buffer .= chr(0x49); $i++;
		$buffer .= chr(0x73); $i++;
		$buffer .= chr(0x64); $i++;
		$buffer .= chr(0x70); $i++;
		$buffer .= chr(0x03); $i++;
		

整体替换成什么样呢？

**Comment by bluerhinos** [comment]
> I am restarting this project so having a clear out of old issues (If you believe this is still valid please reopen)
