### ISSUE TITLE
Not working on cpanel after upload.

### ISSUE THREAD

**Issue by tareq0065** [bluerhinos/phpMQTT#62]
I have tried many servers to use, but it's not working. I am always getting the time out. Is there any special requirement to use the server? Or if I missing something on settings? Actually, I have some dynamic form that contains dynamic fields. After posting any of form I want to do a publish action to the mqtt server. It's working on localhost (wamp server) very good. But after uploading it on my Cpanel hosting it's showing me "time out"

```       
        $server = $config['mqtt_settings']['mqtt_server'];
        $port = $config['mqtt_settings']['mqtt_port'];
        $username = $config['mqtt_settings']['mqtt_username'];
        $password = $config['mqtt_settings']['mqtt_password'];
        $client_id = md5(uniqid(rand(), true));
        $topic = $params['topic_name'];
        unset($params['topic_name']);
        $message = json_encode($params);

        $mqtt = new phpMQTT($server, $port, $client_id);

        if ($mqtt->connect(true, NULL, $username, $password)) {
            $mqtt->publish($topic, $message, 0);

            $ret = [
                'status' => 'success',
                'msg' => "you have successfully published to " . $topic
            ];
                'op_by' => $config['user']->uid
            ]);
            $mqtt->close();
        } else {
            $ret = [
                'status' => 'warning',
                'msg' => "Time out"
            ];
        }
```

**Comment by leonrenkema** [comment]
Is there a MQTT server running? Looks like the code cannot connect to the server.

**Comment by tareq0065** [comment]
How can I check this that my server is good for MQTT or not? Do you have any suggestion?

**Comment by leonrenkema** [comment]
You should make sure that $server/$port is filled with the correct server. If that is the case there is maybe some sort of firewall blocking the connection. You should ask the company that is hosting the server.

**Comment by suraj050kumar** [comment]
Hi Guys,

Have you got any solution for this, i have the same error also.

Thank you

**Comment by bluerhinos** [comment]
> I am restarting this project so having a clear out of old issues (If you believe this is still valid please reopen)

Canned Response: Subscribe is not designed for web requests, it should be used in a long running process.
I do plan to add a subscribeAndWaitForMessage() function #95
