### ISSUE TITLE
Minimum-stability issue

### ISSUE THREAD

**Issue by DustinWatts** [bluerhinos/phpMQTT#64]
Hi there! 

When trying to install true composer i get the following error:

```
[InvalidArgumentException]
  Could not find a version of package bluerhinos/phpmqtt matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.
```
PHP version: 5.6.33-0+deb8u1
Composer Version: 1.6.4

Can anyone help me?

**Comment by msbit** [comment]
Try the following:

    composer require bluerhinos/phpmqtt:dev-master

**Comment by pkrupald024** [comment]
> Try the following:
> 
> ```
> composer require bluerhinos/phpmqtt:dev-master
> ```

Thanks

**Comment by Niek** [comment]
Please update the README to reflect this: ``composer require bluerhinos/phpmqtt=@dev``
