### ISSUE TITLE
Could not find package bluerhinos/phpmqtt.  

### ISSUE THREAD

**Issue by youngda** [bluerhinos/phpMQTT#66]
[root@bemfa mqtt_plat]# composer require bluerhinos/phpmqtt
Do not run Composer as root/super user! See https://getcomposer.org/root for details

                                              
  [InvalidArgumentException]                  
  Could not find package bluerhinos/phpmqtt.  
                                              
  Did you mean this?                          
      bluerhinos/phpmqtt                      
                                              

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

**Comment by akilawickey** [comment]
root@ubuntu-s-1vcpu-1gb-lon1-01:~/phpMQTT# composer require bluerhinos/phpmqtt dev-master
Root package 'bluerhinos/phpmqtt' cannot require itself in its composer.json
Did you accidentally name your root package after an external package?

**Comment by jonah-stfrancois** [comment]
@youngda Worked for me, Thanks!

For those seeing 

composer require bluerhinos/phpmqtt
"[InvalidArgumentException]
Could not find a version of package bluerhinos/phpmqtt matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability."

This worked to fix that for me.

**Comment by suraj050kumar** [comment]
you have to remove namespace Bluerhinos; from phpMQTT.php file.

**Comment by bluerhinos** [comment]
> I am restarting this project so having a clear out of old issues (If you believe this is still valid please reopen)
