### ISSUE TITLE
In phpMQTT.php line 154:Uninitialized string offset: 0

### ISSUE THREAD

**Issue by guoyanjun5** [bluerhinos/phpMQTT#69]
In phpMQTT.php line 154:Uninitialized string offset: 0

**Comment by kingtiwns** [comment]
可能是因为服务器采用mqttv3.1.1版本，要修改代码

**Comment by bluerhinos** [comment]
> I am restarting this project so having a clear out of old issues (If you believe this is still valid please reopen)
