### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by marabesi** [bluerhinos/phpMQTT#71]
I came across the project while researching MQTT libraries to use.

Is this project active? 

As far as I see in the issues there a bunch of them without an answer.

Thank you

**Comment by evandentremont** [comment]
It would seem so.

**Comment by swilson86** [comment]
I could not get this software to publish anything. The examples don't even work. Probably obsolete and nobody is maintaining it.

**Comment by jmarshallpresnell** [comment]
@swilson86 
> I could not get this software to publish anything. The examples don't even work. Probably obsolete and nobody is maintaining it.

By chance, are you using QoS1 or QoS2? If so, then the code doesn't process the messages needed to implement it.

**Comment by bluerhinos** [comment]
> I am restarting this project so having a clear out of old issues (If you believe this is still valid please reopen)

QOS > 0 has feature request #4
