### ISSUE TITLE
How we can implement TLS within this code?

### ISSUE THREAD

**Issue by sandy0110** [bluerhinos/phpMQTT#72]
The code is perfect and work as i expected for me,
but how can i build TLS mqtt code with this code?

**Comment by mohitagnihotri** [comment]
Have you tried to host on the server and check whether it is working or not in browser?

**Comment by xiaotiaowa** [comment]
1.$mqtt = new phpMQTT($server, $port, $client_id, 'cert/ca.crt');

2.phpMQTT.php  line 81:
verify_peer_name => false;





	if ($this->cafile) {
			$socketContext = stream_context_create(["ssl" => [
				"verify_peer_name" => false,
				"cafile" => $this->cafile
				]]);
			$this->socket = stream_socket_client("tls://" . $this->address . ":" . $this->port, $errno, $errstr, 60, STREAM_CLIENT_CONNECT, $socketContext);
		} else {
			$this->socket = stream_socket_client("tcp://" . $this->address . ":" . $this->port, $errno, $errstr, 60, STREAM_CLIENT_CONNECT);
		}

**Comment by msbit** [comment]
Just a note that in the above, you shouldn't set `verify_peer_name` to false unless you absolutely need to, as it opens up the possibility of man in the middle attacks.

**Comment by bluerhinos** [comment]
Feature request #40
