### ISSUE TITLE
I need help!!!

### ISSUE THREAD

**Issue by manfer9559** [bluerhinos/phpMQTT#73]
-------------------------------------------------------------------------------------------------------------------
ESPAÑOL
-------------------------------------------------------------------------------------------------------------------
Hola, yo estoy creando un proyecto que lee la humedad y la temperatura del ambiente y del suelo. Los datos los envió a través de un Arduino a www.cloudmqtt.com. Ahora lo que necesito es enviar los datos de cloudmqtt a mysql, para eso necesito conectarme con PHP a CLOUDMQTT para poder obtener los datos y enviarlos a MYSQL. Pero no me puedo conectar desde PHP a CLOUDMQTT me da un error, se los adjunto al final. Espero que alguien me pueda ayudar con este problema que estoy teniendo, es de suma urgencia y de suma importancia para mi proyecto. El usuario y contraseña son correctos al igual que el puerto.
-------------------------------------------------------------------------------------------------------------------

-------------------------------------------------------------------------------------------------------------------
English
-------------------------------------------------------------------------------------------------------------------
Hello, I am creating a project that reads the humidity and the temperature of the environment and the soil. The data was sent through an Arduino to www.cloudmqtt.com. Now what I need is to send the data from cloudmqtt to mysql, for that I need to connect with PHP to CLOUDMQTT in order to get the data and send it to MYSQL. But I can not connect from PHP to CLOUDMQTT it gives me an error, I attach them to the end. I hope that someone can help me with this problem that I am having, it is of extreme urgency and of great importance for my project. The username and password are correct as is the port.
-------------------------------------------------------------------------------------------------------------------

![codigoerror](https://user-images.githubusercontent.com/43598676/46102738-6dc21280-c1a5-11e8-8ebe-8d53c624ed31.png)
![error](https://user-images.githubusercontent.com/43598676/46102741-6e5aa900-c1a5-11e8-94dd-4235ec18d803.png)

**Comment by bluerhinos** [comment]
> I am restarting this project so having a clear out of old issues (If you believe this is still valid please reopen)
