### ISSUE TITLE
PHP Notice:  fwrite(): send of 268 bytes failed with errno=32 Broken pipe in /var/www/html/tp5/extend/lib/Mqtt.php on line 271

### ISSUE THREAD

**Issue by bobliu2020** [bluerhinos/phpMQTT#76]
并发publish的时候出现这种报错，导致发送失败，请问怎么解决
PHP Notice:  fwrite(): send of 268 bytes failed with errno=32 Broken pipe in /var/www/html/tp5/extend/lib/Mqtt.php on line 271

**Comment by ymstudent** [comment]
我这边遇到了相同的问题，请问您这边解决了么？

**Comment by jellybobbin** [comment]
我也是一直这样的问题

**Comment by bluerhinos** [comment]
> I am restarting this project so having a clear out of old issues (If you believe this is still valid please reopen)

**Comment by gordonf69** [comment]
Hi !

I had this issue today, it happen when the keepalive is too low (default 10 secs) increasing it remove the problem.

**Comment by gordonf69** [comment]
The keepalive work when it's in a "subscribe loop" :

```
while($mqtt->proc()) {

}
```


If it's a "publish" loop, this error happen ... ex:

```
while(1) {
$mqtt->publish($topic, $message, 0,0);
sleep(xxx);
}
```

**Comment by Hao-Wu** [comment]
> Hi !
> 
> I had this issue today, it happen when the keepalive is too low (default 10 secs) increasing it remove the problem.

Hi @gordonf69 , could you please indicate where to increase the keep alive  value?

**Comment by gordonf69** [comment]
> 
> 
> > Hi !
> > I had this issue today, it happen when the keepalive is too low (default 10 secs) increasing it remove the problem.
> 
> Hi @gordonf69 , could you please indicate where to increase the keep alive value?

U can try to modify it line 43 :

    public $keepalive = 10;        /* default keepalive timmer */

**Comment by Hao-Wu** [comment]
A possible cause for this error may be the connections exceed MQTT's max connection number, which is default 1024.
If you can't change MQTT's connection number, try decreasing the concurrent TCP request from your client codes.

For me this works. I decrease my requests from 2000 to 1000, error 32 never occurs.
