### ISSUE TITLE
Publishing to several topics using same connection doesn't work

### ISSUE THREAD

**Issue by fauno** [bluerhinos/phpMQTT#8]
I have this snippet:

``` php
$mqtt = new phpMQTT(MQTT_SERVER, 1883, DOMAIN);                                      
  if ($mqtt->connect()) {
    if (is_array($topic)) {
      foreach ($topic as $t) {
         $mqtt->publish(self::clean_uri($t), $message, 0);
         sleep(1);
      } else {
        $mqtt->publish(self::clean_uri($topic), $message, 0);
      }
      $mqtt->close();
    } else {
      return false;
    }
```

to allow my program to send the same message to several topics (single stream, per user stream, etc.).  i added the `sleep(1)` lines because sending messages one after another only sends the first one. i haven't tried with more than two topics but i notice the time required to send to many more will be long :P

any ideas?

**Comment by bluerhinos** [comment]
I believed this is no longer an issue, as cannot repeat.

> I am restarting this project so having a clear out of old issues (If you believe this is still valid please reopen)
