### ISSUE TITLE
Easy subscribe huge change 

### ISSUE THREAD

**Issue by frmatias** [bluerhinos/phpMQTT#85]
https://packagist.org/packages/frmatias/easy-mqtt
Subcribe changes --

**You only need use 3 statements**
**Check examples files to know what inputs you should use**
$this->connect(params)
$msg = $this->subscribe(params)
$this->close()

**Comment by skyynet** [comment]
Thanks for developing this further.
I'm trying to read my Sonoff Dual R2 Wi-Fi relay wis ESPurna Firmware and have setup my MQTT broker on my local Synology. The Sonoff successfully publishes to /home/garden/mowgli/relay/0 which I can read with MQTTbox on my Mac.

I am trying to read this relay on my local MAMP installation running PHP 7.2 and can't get it to work.

Installing your fork gives me the same error as the original branch:

Fatal error: Uncaught Error: Class 'phpMQTT' not found in subscribe.php:14

When I comment out the namespace Bluerhinos in phpMQTT.php like suggested by another user, subscribe.php is loading forever and not outputting anything.

I have the phpMQTT.php and subscribe.php in the same folder.

Any idea?

`<?php
ini_set('display_errors', '1');
ini_set('error_reporting', E_ALL);

require("phpMQTT.php");


$server = "192.168.1.21";     // change if necessary
$port = 1883;                     // change if necessary
$username = "";                   // set your username
$password = "";                   // set your password
$client_id = "phpMQTT-subscriber"; // make sure this is unique for connecting to sever - you could use uniqid()

$mqtt = new phpMQTT($server, $port, $client_id);

$mqtt->connect(true, NULL, $username, $password);
$topic = '/home/garden/mowgli/relay/0';
$msg = $mqtt->subscribe($topic, 0);
$mqtt->close();`

**Comment by skyynet** [comment]
While it's working, I have two issues.
First reading a value from the broker is very slow
Second I don't know how to read multiple values.
Working sample:
`$mqtt->connect(true, NULL, $username, $password);
$relais0 = $mqtt->subscribe('/home/garden/mowgli/relay/0', 0);
echo 'Relais 0: '.substr($relais0,-1).'<br />';
$mqtt->close();

$mqtt->connect(true, NULL, $username, $password);
$relais1 = $mqtt->subscribe('/home/garden/mowgli/relay/1', 0);
echo 'Relais 1: '.substr($relais1,-1).'<br />';
$mqtt->close();`

There must be a way to read multiple values without connecting and closing every time in between.

**Comment by frmatias** [comment]
you are closing the connection using $mqtt->close(). If you stay with the connection open you can read everything, but php is stateless, so you need call this function again everytime. i'm working in a separete project based on phpMQTT,  search for easyMQTT on packgist. I will treat the returned messenger and also add that a cron job to call the function and save in a database the results, maybe i will focus on laravel.

**Comment by frmatias** [comment]
The easyMQTT i cleaned every useless function.

**Comment by skyynet** [comment]
Thanks. Gonna follow your new repository.

**Comment by bluerhinos** [comment]
Canned Response: Subscribe is not designed for web requests, it should be used in a long running process.
I do plan to add a subscribeAndWaitForMessage() function #95
