### ISSUE TITLE
QoS ignored?

### ISSUE THREAD

**Issue by ld21** [bluerhinos/phpMQTT#86]
Hi guys

I'm trying to publish to an mqtt-broker using QoS of 1. Unfortunately, publishing only works if I use a qos of 0;

// Working aka the message arrives at the broker
$mqtt->publish("$name", "$rgb:$nachricht", 0);  // Topic, Nachricht / QoS

// Not Working aka nothing is arriving at the broker:
$mqtt->publish("$name", "$rgb:$nachricht", 1);  // Topic, Nachricht / QoS

Since I want to be able to store messages on the broker (cleanSession = false), I need a qos > 0 for it to work.

Is there anything I have to keep in mind to publish a message with qos = 1?

Thank you very much, Dani

**Comment by jmarshallpresnell** [comment]
It does not appear that any MQTT messages except PUBLISH (numeric 3) are processed in the code, so QoS1 and QoS2 can not work in the current implementation.

**Comment by bluerhinos** [comment]
QoS has feature request #4
