### ISSUE TITLE
HP Notice:  fwrite(): send of 22 bytes failed with errno=32 Broken pipe in phpMQTT.php on line 214

### ISSUE THREAD

**Issue by damadhav** [bluerhinos/phpMQTT#90]
I want to keep php mqtt script running on background but it is throwing this error

**Comment by bluerhinos** [comment]
> I am restarting this project so having a clear out of old issues (If you believe this is still valid please reopen)

Recent updates should be fix this

**Comment by p1337** [comment]
Getting the same error, with the recent version, after moving to a new server.
is this a port problem?  Worked just fine on the 2 old servers.

**Comment by MikeTheTux** [comment]
I've the same error after running a connection stable over more than a week.

`PHP Notice:  fwrite(): send of 8192 bytes failed with errno=32 Broken pipe in /volume1/public/openHAB/conf/scripts/TD3511/phpMQTT.php on line 435`

Line number is differnt. The error happens when using the `publish` API.

**Comment by tb205gti** [comment]
I have the same error - php notice from fwrite on line 435. :/

Makes the module completely unstable and unusable
